// DO NOT MODIFY
//
// This file is automatically generated by the Firebase setup steps.

export const firebaseConfig = {"projectId":"studio-5587063777-d2e6c","appId":"1:3344718739:web:a893f438d641753df1e666","apiKey":"AIzaSyDfzwpFYfuB5HLbx6iNbuTIBdMHQJuPHYg","authDomain":"studio-5587063777-d2e6c.firebaseapp.com","measurementId":"","messagingSenderId":"3344718739"};
